
# Setup
title:               Rahul Mahanot
email:               thecodeboxed@gmail.com
username:            mahanotrahul
profile_img:         Picture.png
tagline:             ''
description:         'Rahul Mahanot'
baseurl:             '/blog/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rahul Mahanot
  url:               https://twitter.com/RahulMahanot
  email:             thecodeboxed@gmail.com

# collections
collections:
  tales:
    output: true
  categories:
    output: true

# Gems
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
