
# Setup
title:               Rahul Mahanot
email:               thecodeboxed@gmail.com
username:            mahanotrahul
profile_img:         Picture.png
tagline:             ''
description:         'Rahul Mahanot'
baseurl:             '/blog'
paginate:            5
permalink:           pretty
disable_disk_cache:  true

# About/contact
author:
  name:              Rahul Mahanot
  url:               https://twitter.com/RahulMahanot
  email:             thecodeboxed@gmail.com

# collections
collections:
  tales:
    output: true
  categories:
    output: true

# Gems
paginate: 5
paginate_path: "page:num"
plugins:
  - jekyll-paginate
  - jekyll-sitemap

kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Custom vars
version:             1.1.0
google_analytics_id: 'UA-133856785-1'
